name: release
on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        description: "bump version"
        default: minor
        options:
        # major version bumps do only manually
        - minor
        - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: false

jobs:

  run-checks:
    uses: ./.github/workflows/code-checks.yaml
    with:
      branch_ref: ${{ github.ref }}

  release:
    needs: run-checks
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          # Use personal access token to trigger other workflows on tag push
          token: ${{ secrets.TIENDIL_RELEASE_TOKEN }}
